### ISSUE TITLE
Error: Failed to find Server Action "xyz". This request might be from an older or newer deployment

### ISSUE THREAD

**Issue by devrenzz** [kubetail-org/edge-csrf#21]
Error: Failed to find Server Action "xyz". This request might be from an older or newer deployment. Original error: Invariant: Couldn't find action module ID from module map..

1. Error shows once I enable the edge-csrf while using Server Action but if not it works fine as expected.

**Comment by amorey** [comment]
Which version are you using? I haven't seen any errors like this with Edge-CSRF and it sounds like an issue with the Server Action implementation itself. Here are two reference examples you can use for Server Actions and Edge-CSRF:
https://github.com/kubetail-org/edge-csrf/blob/main/examples/next14-approuter-server-action-form-submission
https://github.com/kubetail-org/edge-csrf/blob/main/examples/next14-approuter-server-action-non-form-submission

**Comment by devrenzz** [comment]
I use https://next-safe-action.dev/ for handling server actions. I also tried adding the csrf_token to the payload but seems still showing the same error. I think maybe this is from nextjs issue alone.

**Comment by amorey** [comment]
Can you share a code example that’s produces the error?

**Comment by devrenzz** [comment]
```ts

// create-profile-form.tsx
'use client';

const CreateProfileForm = ({ handleCloseModal }: Props) => {
  const form = useForm<CreateProfilePayload>({
    resolver: zodResolver(CreateProfileSchema)
  });
  const router = useRouter();

  const { execute, status } = useAction(createProfile, {
    onSuccess: (data) => {
      const profile = data.data;

      router.refresh();
      router.push(`${ROUTES.Profiles}/${profile?.id}`);
      handleCloseModal();
    }
  });

  const isExecuting = status === 'executing';

  const handleNewProfile = (payload: CreateProfilePayload) => execute(payload);

  return (
    <div className="mt-4">
      <FormProvider {...form}>
        <form onSubmit={form.handleSubmit(handleNewProfile)}>
          <FormInput
            name="name"
            label="Profile Name"
            placeholder="My Awesome Profile"
          />

          <FormButton
            type="submit"
            variant={'dark'}
            className="py-3 w-full mt-6"
            loading={isExecuting}
          >
            Create Profile
          </FormButton>
        </form>
      </FormProvider>
    </div>
  );
};

export default CreateProfileForm;

// actions.ts 
'use server';

export const createProfile = authAction(
  CreateProfileSchema,
  async (payload, ctx) => {
    if (!payload) return { message: 'Invalid input', status: 400, code: null };

    const { error, status, data } = await supabase
      .from('profiles')
      .insert({ name: payload.name, user_id: ctx.userId })
      .select('*')
      .single();

    if (error) {
      return { message: error.message, status, code: error.code };
    }

    revalidatePath(ROUTES.Profiles);

    return { message: 'Added successfully!', status: 201, data };
  }
);

```ts

**Comment by devrenzz** [comment]
I remove the imports. Also I found this reddit https://www.reddit.com/r/nextjs/comments/177tjld/nextjs_middleware_w_server_actions/ **MinimalMarzipan** comment

**Comment by devrenzz** [comment]
I downgraded to 14.0.1 and error is gone but I got a new error. 

>  ⨯ Error [TypeError]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object
    at new NodeError (node:internal/errors:405:5)
    at Function.from (node:buffer:324:9)
    at atob (file://D:\app\node_modules\.pnpm\next@14.0.1_@babel+core@7.23.9_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\edge-runtime\index.js:1:657096)
    at atou (webpack-internal:///(middleware)/./node_modules/.pnpm/edge-csrf@1.0.9_next@14.0.1/node_modules/edge-csrf/dist/esm/util.js:34:13)       
    at eval (webpack-internal:///(middleware)/./node_modules/.pnpm/edge-csrf@1.0.9_next@14.0.1/node_modules/edge-csrf/dist/esm/index.js:34:118)     
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DevServer.runMiddleware (file://D:\app\node_modules\.pnpm\next@14.0.1_@babel+core@7.23.9_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\next-server.js:1029:24)
    at async DevServer.runMiddleware (file://D:\app\node_modules\.pnpm\next@14.0.1_@babel+core@7.23.9_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\dev\next-dev-server.js:258:28)
    at async NextNodeServer.handleCatchallMiddlewareRequest (file://D:\app\node_modules\.pnpm\next@14.0.1_@babel+core@7.23.9_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\next-server.js:321:26)
    at async DevServer.handleRequestImpl (file://D:\app\node_modules\.pnpm\next@14.0.1_@babel+core@7.23.9_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\base-server.js:757:28) {
  middleware: true
}
 ⨯ SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)

**Comment by amorey** [comment]
Sorry, I can't tell from that code snippet what the problem is. Based on the traceback in your last message, it looks like you're using an object instance as the CSRF token you're passing to edge-csrf but your code snippet doesn't set the CSRF token so I can't be sure. Can you share a minimal example that demonstrates the bug? Ideally, if you can create a new repo with next + next-safe-action + edge-csrf that throws an error then I can debug it more easily.

**Comment by devrenzz** [comment]
It is working now with next-safe-action. I just created another function to add the csrfToken. This is how I did it.

```ts
export const createProfileAction = async (
  csrfToken: string,
  payload: CreateProfilePayload
) => {
  const { data } = await createProfile(payload);
  return data;
};

**Comment by amorey** [comment]
Great to hear you got it working! Let me know if you run into any more problems with the edge-csrf integration.
