### ISSUE TITLE
Custom NextJs server problem

### ISSUE THREAD

**Issue by mkoumila** [kubetail-org/edge-csrf#40]
I'm using a custom Node.js server to run my development environment as described in the Next.js [documentation](https://nextjs.org/docs/pages/building-your-application/configuring/custom-server)

Since I'm using a custom server, I have my middleware within it and have added the package's functionality as shown in the example below. Unfortunately, my project is throwing errors and nothing is working. Can anyone provide some guidance?

```
const { createServer } = require('http')
const { parse } = require('url')
const next = require('next')
 
const dev = process.env.NODE_ENV !== 'production'
const hostname = 'localhost'
const port = 3000
// when using middleware hostname and port must be provided below
const app = next({ dev, hostname, port })
const handle = app.getRequestHandler()
const csrf = require("@edge-csrf/nextjs")

// Initialize CSRF protection middleware
const csrfMiddleware = csrf.createCsrfMiddleware({
    cookie: {
        secure: true
    },
})
 
app.prepare().then(() => {
  createServer(async (req, res) => {
    try {
      const parsedUrl = parse(req.url, true)
      const { pathname, query } = parsedUrl
 
      // Apply CSRF middleware
      await csrfMiddleware(req, res)
      
      if (pathname === '/a') {
        await app.render(req, res, '/a', query)
      } else if (pathname === '/b') {
        await app.render(req, res, '/b', query)
      } else {
        await handle(req, res, parsedUrl)
      }
    } catch (err) {
      console.error('Error occurred handling', req.url, err)
      res.statusCode = 500
      res.end('internal server error')
    }
  })
    .once('error', (err) => {
      console.error(err)
      process.exit(1)
    })
    .listen(port, () => {
      console.log(> Ready on http://${hostname}:${port}`)
    })
})
```

![image](https://github.com/kubetail-org/edge-csrf/assets/108822271/10c289ff-410c-4c1c-8d9e-4f590b0b6798)

**Comment by amorey** [comment]
In the custom server the `req` and `res` objects being passed to the listener are of type `Request` and `ServerResponse` but the `@edge-csrf/nextjs` methods expect `NextRequest` and `NextResponse` so calling middleware methods there won't work.

I think you have two options:
1. If you need CSRF protection for the entire custom server then you can implement it with lower-level methods from `@edge-csrf/core`. If this is a common enough request we can publish the implementation as a new package (e.g. `@edge-csrf/node`).
2. If you just want CSRF protection for the Next app you should be able to add it to the `middleware.js` file as normal

**Comment by amorey** [comment]
@mkoumila Have you been able to get edge-csrf working with your custom server? If you need to add CSRF protection at the level of the node server, we should be able to re-use the code from the new Express integration to implement csrf protection for node `createServer()`.

**Comment by mkoumila** [comment]
Hello @amorey ,
I haven't tried it yet because i left my laptop at the office, I'll try the `@edge-csrf/core` forst thing tomorrow and see if it's working.
Which function should i use specifically in this case because there are a lot from the core examples.
Thanks

**Comment by mkoumila** [comment]
Hello @amorey ,
Unfortunately i wasn't able to make it work for my custom Node.js server in my NextJs app, I tried using the new Express example ( by the way thank you for that 🙏🏼 ) and it didn't work, probably because i'm not using Express in my project ?! ( Sorry my backend experience isn't that strong )
Is there an example or a way to use it in vanilla nodejs code like the example that i have provided above? 
Thanks

**Comment by amorey** [comment]
No worries, I tweaked the Express code and published a new implementation for Node HTTP: https://www.npmjs.com/package/@edge-csrf/node-http

It's also documented on the repo as well: https://github.com/kubetail-org/edge-csrf

Try that and let me know if it works.

**Comment by amorey** [comment]
Awesome! 🥳 Happy to hear it's working for you! Let me know if you run into any problems.

**Comment by mkoumila** [comment]
Hello @amorey,

I'm encountering an issue with using [@edge-csrf/node-http](https://www.npmjs.com/package/@edge-csrf/node-http) in production environment with Docker.

In the development environment, everything works perfectly. However, when I test it in production using Docker, it throws the error shown in the attached photo. Upon investigation, I discovered that **@edge-csrf/node-http** isn't installed and is not available in the node_modules directory.

Here is some additional information:

- The package isn't listed in devDependencies.
- My Node.js version on my local machine is v18.18.2, while in my Docker image, it is v18.20.2.
- All other packages are installed and available in the node_modules folder except for **@edge-csrf/node-http**
- I built the Docker image without using the cache, but the issue persists.
- My project is a NextJs app with a custom nodejs server

Do you have any idea?

Thank you!

<img width="784" alt="image" src="https://github.com/kubetail-org/edge-csrf/assets/108822271/8f6fadce-380c-4558-8b45-bef9ea8dfe24">

**Comment by amorey** [comment]
Is the module listed in the “dependencies” of package.json? What are the build commands from the Docker file? What is the run command?

**Comment by mkoumila** [comment]
@amorey Yes, the module is listed in the dependencies section of our package.json.

Our Dockerfile is quite complex and includes many operations, but none of them modify the packages. It only installs them. This is the first time Docker hasn't install a package listed in package.json without throwing an error during installation phase.

The commands I run are: `docker compose build && docker compose up`

I just want to ask if this is normal behavior for the package. Otherwise, it might be related to our project structure, and I should investigate further.

**Comment by amorey** [comment]
If the problem is that the module is missing from ‘node_modules’ then that’s not normal behavior. I’m wondering if it’s an issue with how you’re building and deploying the Next app. If you’re using ‘next build’ to build the app then you probably have to create a separate build step for the server that installs the module explicitly because it’s used by the server, not the app.

Alternatively, you can use @edge-csrf/nextjs in your Next middleware and deploy the custom server without csrf protection.

**Comment by mkoumila** [comment]
You gave me a great hint, which worked.
i had to copy the package in Dockerfile like this:
`COPY --from=builder_starter --chown=1001:1001 /app/node_modules/@edge-csrf/ ./node_modules/@edge-csrf`

Thank you @amorey 🙏🏼
