### ISSUE TITLE
Add support for partitioned cookies

### ISSUE THREAD

**Issue by bookernath** [kubetail-org/edge-csrf#54]
For cookies set within iframes it's helpful to set the `Partitioned` flag to have compatibility with [Chrome's CHIPS update](https://developers.google.com/privacy-sandbox/3pcd/chips).

Example usage might be:
```javascript
// middleware.ts

import { createCsrfMiddleware } from '@edge-csrf/nextjs';

// initalize csrf protection middleware
const csrfMiddleware = createCsrfMiddleware({
  cookie: {
    secure: process.env.NODE_ENV === 'production',
    partitioned: true, // add this new arg
  },
});

export const middleware = csrfMiddleware;
```

**Comment by amorey** [comment]
Thanks for the suggestion! I added support for the `partitioned` attribute and published a new release candidate (v2.3.0-rc1):
https://www.npmjs.com/package/@edge-csrf/nextjs/v/2.3.0-rc1?activeTab=versions

Let me know if it's working as expected.

**Comment by amorey** [comment]
@bookernath Have you had a chance to try out the release candidate (v2.3.0-rc1)? Let me know if it's working for you and I can cut a new release.
https://www.npmjs.com/package/@edge-csrf/nextjs/v/2.3.0-rc1?activeTab=versions

**Comment by amorey** [comment]
This feature is live in v2.3.0
