### ISSUE TITLE
Invalid CSRF error when accessing from public ip

### ISSUE THREAD

**Issue by anvishinc** [kubetail-org/edge-csrf#58]
I recently added edge-csrf as an middleware and all was working fine in development and when I access the site from localhost the middleware works as you would image. But when I pushed it to production and accessed it from the public IP/domain it says invalid CSRF token, but it still works fine in local host. Did I miss something?
Here is the middleware file incase you need it

```middleware.ts
import { createCsrfMiddleware } from "@edge-csrf/nextjs";

// Initialize CSRF protection middleware
const csrfMiddleware = createCsrfMiddleware({
  cookie: {
    secure: true,
  },
});

export const middleware = csrfMiddleware;

export const config = {
  matcher: [
    "/contact/:path*",
    "/office/:path*",
    "/careers/:path*",
    "/api/form_data/:path*",
  ],
};
```
I am trying to send data from /contact or /office or /careers to /api/form_data

**Comment by anvishinc** [comment]
@amorey sorry to disturb you but would you be able to help me out here

**Comment by mkoumila** [comment]
Hi @anvishinc ,
 - Did you deploy in Vercel?
 - What is the value of CSRF token in production? is it **missing**

**Comment by anvishinc** [comment]
Yes tried vercel and even my own server.And no, not missing, I checked multiple times and it does pass an csrf token but it just gets validated as invalid

**Comment by amorey** [comment]
@anvishinc Sorry you're having problems. Can you share an example that demonstrates this error?

**Comment by anvishinc** [comment]
@amorey Turns out that was it, my frontend and my backend was decoupled and for testing purposes I hadn't yet added a SSL certificate and I believe that was the reason why this happened. Added an SSL cert to it just now and it gets validated just fine. Anyways, thanks @amorey & @mkoumila for the quick response and the help, and sorry for wasting your time with a dumb mistake on my end.

**Comment by amorey** [comment]
Awesome! Good to hear you figured it out. Let me know if you run into any other problems or have any questions about the library.
