### ISSUE TITLE
The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object

### ISSUE THREAD

**Issue by svarup** [kubetail-org/edge-csrf#63]
When we use server action with [@tanstack/react-query](https://www.npmjs.com/package/@tanstack/react-query) and useMutation function its give me below error.

```
The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object
```

This is because [edge-csrf](https://github.com/kubetail-org/edge-csrf) package required  the first argument as csrf token as string and "useMutation" can not pass multiple args we can pass only one arguments, if we have to pass multiple args then we have to pass it in object.

so due to "useMutation" we can not pass first args as csrf token as string.

here it is the [codesandbox ](https://codesandbox.io/p/devbox/rdpvxn)for easy to debug

**Comment by amorey** [comment]
Thanks for the bug report. I just published a version that handles this case as a release candidate (2.4.0-rc1):
https://www.npmjs.com/package/@edge-csrf/nextjs/v/2.4.0-rc1

To use it you'll have to change your token name from `csrfToken` to `csrf_token`, then everything should work. Would it be helpful to make the token's name configurable? The configuration would look like this:

```
// middleware.ts

import { CsrfError, createCsrfProtect } from "@edge-csrf/nextjs";
import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";

// initalize csrf protection method
const csrfProtect = createCsrfProtect({
  cookie: {
    secure: process.env.NODE_ENV === "production",
  },
  token: {
    name: 'csrfToken',
  },
});

// Next.js middleware function
export const middleware = async (request: NextRequest) => {
  const response = NextResponse.next();

  try {
    await csrfProtect(request, response);
  } catch (err) {
    if (err instanceof CsrfError)
      return new NextResponse("invalid csrf token", { status: 403 });
    throw err;
  }

  return response;
};

```

**Comment by svarup** [comment]
@amorey yes its working now after updating the package to [2.4.0-rc1](https://www.npmjs.com/package/@edge-csrf/nextjs/v/2.4.0-rc1). and yes it would be great if we have the option to configure the token name.

**Comment by amorey** [comment]
Great, thanks for checking. Here's a new release candidate with a configurable token field name (2.4.0-rc2):
https://www.npmjs.com/package/@edge-csrf/nextjs/v/2.4.0-rc2

You can configure it like this:
```
const csrfProtect = createCsrfProtect({
  cookie: {
    secure: process.env.NODE_ENV === "production",
  },
  token: {
    fieldName: 'csrfToken',
  },
});
```

Let me know if everything is working.

**Comment by svarup** [comment]
@amorey yes its working, we can now configure the param name of object which contains the csrf token on [2.4.0-rc2](https://www.npmjs.com/package/@edge-csrf/nextjs/v/2.4.0-rc2). Thanks for the update. i really appreciate it.

[codesandbox of 2.4.0-rc2](https://codesandbox.io/p/devbox/csrf-forked-ttphmq)

**Comment by amorey** [comment]
Awesome! I released a new stable version with the new features (2.5.0):
https://www.npmjs.com/package/@edge-csrf/nextjs/v/2.5.0

Let me know if you run into any other problems.
