### ISSUE TITLE
Feature Request: Simplify CSRF Token Handling in Next.js 13+

### ISSUE THREAD

**Issue by svarup** [kubetail-org/edge-csrf#67]
This feature request is specific to Next.js 13 and above.

Currently, we need to pass the CSRF token in the "body" of every API or server action request, as well as in the method that handles the request, which can be tedious. To simplify this process:

In Next.js, it's possible to pass [custom request headers via middleware](https://nextjs.org/docs/app/building-your-application/routing/middleware#setting-headers). If the package could first verify the CSRF token from the request header, and only fall back to verifying it from the request body if it's missing in the header, it would streamline CSRF protection. This approach allows us to set the CSRF token in the request header within middleware as a one-time setup for all requests (except those specified in the ignoreMethods config).

While users can manually set the CSRF token in the request header via middleware, it would be even more convenient if the package provided a method to automatically set the CSRF token in the request headers for all methods not included in the ignoreMethods configuration.

For backward compatibility, we could introduce a new config option to specify where the CSRF token should be retrieved for verification. By default, this option could be set to "body," but users could switch it to "header" or "both" ("both" meaning the token is first checked in the header, and if not found, then it will verify from the body).

**Comment by amorey** [comment]
Edge-CSRF already checks for the token in the `x-csrf-token` request header. Here's an example from the unit tests:
https://github.com/kubetail-org/edge-csrf/blob/main/shared/src/util.test.ts#L59-L67

Let me know if that addresses your issue.

**Comment by svarup** [comment]
Thank you @amorey , i thought we can only pass csrf by body only, as its not mentioned any where in readme file.

**Comment by amorey** [comment]
No worries, I added a note about the `X-CSRF-Token` request header to the README so hopefully it will be easier to find in the future. Let me know if you run into any issues using the request header token method.

**Comment by svarup** [comment]
@amorey is there any way to set the token's ttl or expiry like JET token has? So, on token verification, it will be marked as an invalid token if it's expired.

**Comment by amorey** [comment]
The token itself doesn't have a TTL but you can control the lifetime by setting the `maxAge` of the csrf secret cookie. By default `maxAge` is `undefined` which makes it a session cookie.
