### ISSUE TITLE
Unable to Access CSRF Token in getServerSideProps Despite _csrfSecret Cookie Being Set

### ISSUE THREAD

**Issue by nishtha2401** [kubetail-org/edge-csrf#68]
1. When I load the application, the _csrfSecret cookie is correctly set in the browser.
2. However, in getServerSideProps, I'm unable to retrieve the CSRF token using res.getHeader('x-csrf-token').

**Comment by amorey** [comment]
Which version of Next.js are you running? Can you share code so I can reproduce the problem?

Here are some examples of using using edge-csrf with Next.js 13 & 14 with pages router:
https://github.com/kubetail-org/edge-csrf/tree/main/examples/next13-pagesrouter-html-submission
https://github.com/kubetail-org/edge-csrf/tree/main/examples/next14-pagesrouter-html-submission

**Comment by nishtha2401** [comment]
1. I am using Next.js 13.4.7
2.  I was able to successfully fetch the token using: `const key = req.headers["x-csrf-token"];`
3. `res.getHeader("x-csrf-token"); `returned undefined

**Comment by amorey** [comment]
Did you try using "X-CSRF-Token" (with caps)? Here's an Next.js 13 example with  `res.getHeader()`:
https://github.com/kubetail-org/edge-csrf/blob/main/examples/next14-pagesrouter-html-submission/pages/index.tsx

**Comment by nishtha2401** [comment]
Yes, it is undefined.

**Comment by amorey** [comment]
Sorry, I just remembered that there's was a bug in Next.js 13.3.X-13.4.X that affected headers set in middleware:
https://github.com/vercel/next.js/issues/48083
https://github.com/vercel/next.js/issues/48546

Here's the previous discussion about this on the edge-csrf repo: 
https://github.com/kubetail-org/edge-csrf/issues/8

If you upgrade to 13.5.X it should fix the problem.
