### ISSUE TITLE
Generating a new token in getServerSideProps without refreshing

### ISSUE THREAD

**Issue by loba-b** [kubetail-org/edge-csrf#69]
Hi, I'm using Next.js with Page Routing. My implementation is similar to the one found here: https://github.com/kubetail-org/edge-csrf/tree/main/examples/next14-pagesrouter-html-submission

I'm generating a CSRF token in `getServerSideProps`:
```tsx
export const getServerSideProps: GetServerSideProps = async ({ res }) => {
  const csrfToken = res.getHeader('X-CSRF-Token') || 'missing';
  return { props: { csrfToken } };
};
```
I'm passing this token via the Context API to a deeper component, where I'm using Axios to get a response from the endpoint:
```tsx
const response: AxiosResponse<{ status: boolean }> = await axios.post(`}/api/endpoint`, {
    q: value,
    csrf_token: csrfToken
}, {
    headers: {
        'Content-Type': 'application/json'
    }
 });
```
After calling the endpoint, I don't generate a new token.

If possible, I would prefer not to create a separate endpoint for the token. I found a solution to refresh the page without reloading [here](https://github.com/vercel/next.js/discussions/12646) but it seems more like a [bug](https://stackoverflow.com/questions/74755177/nextjs-attempted-to-hard-navigate-to-the-same-url-error-while-passing-query-str). 

Do you know how to handle this, or am I misunderstanding something and should approach it differently?

**Comment by amorey** [comment]
In terms of edge-csrf, you don't need to generate a new token. You can use the same token for subsequent requests. Does that solve the problem?

**Comment by loba-b** [comment]
Thanks for the reply.
Isn't the whole point of signed double submit cookie pattern that each token should be unique and valid for a single request, similar to a one-time password (OTP)? This ensures that the token cannot be reused, preventing unauthorized requests?

**Comment by amorey** [comment]
With the signed double-submit cookie pattern the security comes from the fact that in order to trick a user into making a request, an attacker would have to forge both the token and the cookie. If an attacker were somehow able to forge the token and cookie then making the token singe-use wouldn't enhance security because they'd be able to generate a new single-use token as easily as a one-time one, but it would make it harder to scale because you'd also have to track token usage.

**Comment by loba-b** [comment]
Ok, it make sense, thank you for explanation.

Btw: are you considering adding the ability to include custom data or a secret key to the token in the library, allowing it to be unhashed (if you know secret key) and the data verified?

**Comment by amorey** [comment]
Currently, the library signs tokens with the value from the cookie and verifies that the token and the cookie match for validation. I think adding custom data to the token is outside the scope of the project but you could implement it yourself with a session cookie library.

**Comment by loba-b** [comment]
Thank you @amorey.
