### ISSUE TITLE
Next.js v15 support

### ISSUE THREAD

**Issue by stefee** [kubetail-org/edge-csrf#71]
Add official support for Next.js v15.

See [blog post](https://nextjs.org/blog/next-15) and [upgrade guide](https://nextjs.org/docs/app/building-your-application/upgrading/version-15).

**Comment by amorey** [comment]
Awesome! Thanks for sharing! Did you have to change any of the Edge-CSRF source files? From the PR it looks like you didn't but just wanted to make sure.

**Comment by stefee** [comment]
No problem - I don’t think any source changes are required to the library just based on a few searches of the codebase and reading the changelog on the Next.js side.

I also haven’t tested this super thoroughly, so you’ll have to let me know how you’d like to approach regression testing this. Let me know how I can help.

**Comment by amorey** [comment]
I played around with it and it seems to work as expected without modification. The only issue I found is that server action error handling with <forms> seems to have changed. Previously, non-200 responses would just be ignored in the app. Now they trigger an "Unhandled Runtime Error" in the app. I think this should be fixed on the Next.js side but we'll see.

Anyways, the only issue I found with the PR is this message when I run `pnpm dev` in the next15-* examples:
```
 ⚠ Invalid next.config.js options detected: 
 ⚠     Unrecognized key(s) in object: 'swcMinify'
 ⚠ See more info here: https://nextjs.org/docs/messages/invalid-next-config
```

I also go this additional message in next15-approuter-html-submission:
```
We detected TypeScript in your project and reconfigured your tsconfig.json file for you.
   The following suggested values were added to your tsconfig.json. These values can be changed to fit your project's needs:

   	- target was set to ES2017 (For top-level `await`. Note: Next.js only polyfills for the esmodules target.)
```

**Comment by amorey** [comment]
The PR is merged. Thanks for your help!!!

**Comment by stefee** [comment]
Yay - you're welcome @amorey! This package is super useful.
