### ISSUE TITLE
CSRF token not transmitted to server action

### ISSUE THREAD

**Issue by alexandrumogic** [kubetail-org/edge-csrf#79]
Hi,

I am using createCsrfMiddleware in middleware.ts, and client receives correctly the CSRF token. However, if I try to call a server action directly (not through a form), the POST request does not pass because 403 invalid csrf token (the token is not received in the middleware). Seems like there is no way to transmit the CSRF token to the server action. Do you have any idea how can this be solved?

Many thanks!

**Comment by amorey** [comment]
Which version of Next.js are you using? Here are some examples of how to use Edge-CSRF with non-form server actions for Next.js 14, and 15:
https://github.com/kubetail-org/edge-csrf/tree/main/examples/next14-approuter-server-action-non-form-submission
https://github.com/kubetail-org/edge-csrf/tree/main/examples/next15-approuter-server-action-non-form-submission

If you can share some code I can give more specific tips on how to solve the problem.
