### ISSUE TITLE
Confused about the next.js example

### ISSUE THREAD

**Issue by theogravity** [kubetail-org/edge-csrf#83]
It has `<input type="hidden" value={csrfToken}>`. There's no field name? 

I thought I could send the CSRF value through the `x-csrf-token` header when doing my `fetch` call to an `/api` route via app router, but that doesn't seem to work.

Also tried passing it as a form field (JSON body) called `csrf_token`.

**Comment by theogravity** [comment]
Update: `csrf_token` does work. I use my page in an iFrame and the cookie settings around it was not causing the cookie to be passed through to the `/api` endpoint.

The example does need to be updated to have the proper field name though.

**Comment by amorey** [comment]
Thanks, I fixed the examples in README.

Were you able to fix the cookie issue? The cookie options are documented in the README for each integration package:
https://github.com/kubetail-org/edge-csrf/tree/main/packages/nextjs
